inherit_from: ./configs/Dynamic/YouTube/youtube.yaml
scene: stmoritz_05

stride: 5

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/stmoritz_05
cam:  #intrinsic is different per scene in YouTube Dataset
  H: 720
  W: 1280
  H_out: 360
  W_out: 640
  fx: 656.695232
  fy: 656.695232
  cx: 640.000000
  cy: 360.000000
