inherit_from: ./configs/wildgs_slam.yaml

dataset: 'youtube'

data:
  root_folder: ./datasets/YouTube
  output: ./Outputs/YouTube
  
cam:  #intrinsic is slightly different per seq
  png_depth_scale: 1.0 #for depth image in npy format
  H: 1080
  W: 1920
  fx: 190.000000
  fy: 190.000000
  cx: 199.500000
  cy: 199.500000
  distortion: [0, 0, 0, 0, 0]
  H_out: 360
  W_out: 640

tracking:
  buffer: 500

mapping:
  Training:
    alpha: 0.6 # Increase this value to make rendering loss weighs more on rgb rather than depth
  uncertainty_params:
    uncer_depth_mult: 0.01
